# Generated by Django 5.2.8 on 2025-11-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_alter_student_current_semester'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='colleges.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'enrollment')},
        ),
    ]
