# Generated by Django 5.2.8 on 2025-11-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_alter_student_current_semester'),
        ('courses', '0002_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='colleges.enrollment'),
        ),
    ]
